# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Frz
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab_pausable_contextual_help
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: jupyterlab_pausable_contextual_help
repository: ''
test: false
viewer_name: ''

